### ISSUE TITLE
Battery Charge % Indicator [Feature Request]

### ISSUE THREAD

**Issue by MountainX** [MarianArlt/sddm-sugar-dark#12]
I love this theme. I have converted about 20 people over to it. The only feature missing for me is a battery charge % indicator.

**Comment by MarianArlt** [comment]
@MountainX Thank you for the love. Glad you like it that much. I would love this myself but there's a huge catch here.

SDDM itself does not provide any means to implement this. KDE has got around this by passing several hardware functions to their themes. I could access these by importing KDE specific modules. In return it would render my theme incompatible with other Desktop Environments other than KDE.
This is exactly why I made two versions of the Chili greeter. Sadly it's a lot more work to publish everything twice and DE specific. I may think about it for other newer themes (try out Sugar Candy).

Sorry to disappoint you for now.
