### ISSUE TITLE
Giant virtual keyboard

### ISSUE THREAD

**Issue by abers** [MarianArlt/sddm-sugar-dark#4]
On Kubuntu 18.10 when the theme is installed editing any text box, such as entering a password, pops up a giant virtual keyboard on the bottom half of the screen and the top half turns black. Is there any way to disable this behaviour in theme.conf?

**Comment by MarianArlt** [comment]
@abers This is a serious and old yet not tackled issue with SDDM and the virtual keyboard. By default SDDM makes the theme creators responsible to avoid this,...which is utter crap...[See here](https://github.com/sddm/sddm/issues/952)

In the mean time you can edit your `/etc/sddm.conf` and replace

`InputMethod=qtvirtualkeyboard`
with
`InputMethod=`

**Comment by Bumbadawg** [comment]
Removing the virtualkeyboard on ubuntu might break dependencies and you'll have to reinstall neon-desktop if you're using plasma for instance.
