### ISSUE TITLE
Have the possibility to hide the password when typing

### ISSUE THREAD

**Issue by Bumbadawg** [MarianArlt/sddm-sugar-dark#9]
It's convenient for people alone on their computer to have their password letters show up. But i don't want people around me watching it. Is it possible to disable the letter preview ?
Thanks for making the addon. 

unrelated: You might inform users to add this tweak since you can't modify it yourself https://github.com/MarianArlt/sddm-sugar-dark/issues/4
It's one step that will make regular users avoid using your theme.
Cheers

**Comment by MarianArlt** [comment]
Please see the [Sugar Wiki](https://github.com/MarianArlt/sddm-sugar-light/wiki/Interface-Behavior#user-interface) on `ForceHideCompletePassword=`. Just go to your theme.conf and set this to true ;)

As for #4 I'm working on something.

**Comment by Bumbadawg** [comment]
Top response, thanks @MarianArlt !

**Comment by xstable** [comment]
Nice that there is an option for this to configure it.
But in my opinion, the default setting should be to `not show` the password. At least for security reasons!

**Comment by winkelnp** [comment]
Sorry to reopen(-ish) a dead thread, but for some reason setting the option in a separate `theme.conf.user` (as recommended on the arch wiki) doesn't change anything for me, only when I go in and change the `theme.conf` file itself.

other things I have set in `theme.conf.user` like the background work just fine
